baseURL = "https://mattwillflood.github.io/Bio/"
languageCode = "en-ie"
title = "Matt Flood"
theme = "terminal"
enableemoji = true

paginate = 5

[params]

  hidedate = true

  custom_css = ["css/form.css"]

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = ""

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false


[languages]
  [languages.en]
    languageName = "English"
    title = "Matt Flood"
    subtitle = "A little bit about me"
    owner = "Matthew W. Flood"
    keywords = ""
    copyright = "© Copyright 2021,  Matthew W. Flood"
    menuMore = "Show more"
    readMore = "Have a look"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "|> Matt Flood"
      logoHomeLink = "/Bio"

    [languages.en.menu]   
      [[languages.en.menu.main]]
        identifier = "About"
        name = "About"
        url = "/"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "Research"
        name = "Research"
        url = "/Research"
        weight = 2  

    
    # [[languages.en.menu.main.children]]
    #    identifier = "EMG Entropy"
    #    name = "TEMP"
    #    url = "/xx/TEMP"
    #    parent = "Research"
    #    weight = 2 


      [[languages.en.menu.main]]
        identifier = "Publications"
        name = "Publications"
        url = "/Publications"
        weight = 3

      [[languages.en.menu.main]]
        identifier = "Honours"
        name = "Honours"
        url = "/Honours"
        weight = 4



